services:
  - type: web
    name: movie-flix
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 web.py
    plan: free
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: MONGO_DB_URI
        value: your_mongo_uri
      - key: OWNER_ID
        value: your_owner_id
      - key: LOG_CHANNEL
        value: your_log_channel_id
      - key: FILE_CHANNEL
        value: your_file_channel_id
